language: node_js
node_js:
- '9'
cache:
  directories:
  - node_modules
script:
- yarn test
- yarn build
deploy:
  provider: heroku
  app: sg-traffic
  api_key:
    secure: C4GkdE+vXMDHVtLq4cKEmfV5z1jjoDqJD51K0/yuxdpD3NP1qgw5KlwPn7QCz/dItetjQtERa/6xoeaSuWEBUQytEQFXAtxo+LbHj3wRWC9Pm6RLotKmSiufcI8cpcju+ZAk1ufN1VmN1wDGtReQauSs2YUZAx6uvwZwo7vqOyQSPx10bTStK3x6Uo9K8ZzjyYhrocu0k/tKo457ujQmu3WegI+8wMTplo0+Fp/5y4TTnWvwGOASLi7jKu4xxqwPJ81ILnMw1Z1CnGkYnQ5BvVU3fy747sO7Q7Tzz/VRHpZL/GSIru4jRzXaWbF72WMACtQ8uD+5cXfhRhr2IkaZm+RxDwmL4h7BCdMtv3abfXXlBRko9HdUSaCSdpcHcDhLakwJ3IpvayN06Djfm1zSCf6aHy5iywY1GIiIiQdz2db8Uy5EDYagYc8uNTh2UPRWnxI4GHAZoFbqMOOmXMzrSAVcSms+3XKC8Yb/bi0W8jStqXpCekPVKaqKWmEVI+qf76HR9B8BA//F9HpVVUi9S1+hBWYFAkK0njXswWTJMkkaGHoMdtmvsHpcQRValQVJZOJ/ygLVMKlvKQQOlXkbYo5KdxyN1zDncJFhxQ2Sm3XhpSNxz/bx8ho47MXTX2F7+PuPq/4FLKndn6JCUYMrJXRJXmH2aUEkLx8qBKffUgw=
